### ISSUE TITLE
NameError: undefined local variable or method `deny_access`

### ISSUE THREAD

**Issue by davidgf** [thoughtbot/clearance#449]
I'm using `Ruby 2.1.2`, `Rails  4.0.2` and `Clearance 1.4.0`. It seems that `ActionController::TestCase` it's not being extended with `Clearance::Testing::Matchers`, as whenever I try to use the `deny_access` method in my functional tests, it raises this error: `NameError: undefined local variable or method 'deny_access'`.
My `test_helper.rb` looks like this:

```ruby
ENV["RAILS_ENV"] ||= "test"
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'
require 'clearance/test_unit'

class ActiveSupport::TestCase
  ActiveRecord::Migration.check_pending!

  fixtures :all
end
```

And the test that raises the error:

```ruby
require 'test_helper'

class Admin::PostsControllerTest < ActionController::TestCase

	context "a guest user" do
		
	  setup do
	    @post = FactoryGirl.create(:post)
	  end

	  should "be redirected on index" do
	    get :index
	    assert deny_access
	  end
    end
end
```

**Comment by derekprior** [comment]
I played with this a bit today and came away befuddled. What @croaky suggests gives you the error you mention because shoulda/test-unit seems to lose access to the request between the setup block and the should statement. I really know nothing about shoulda context and cant explain why this happens or what a workaround could be?

I was able to get Test::Unit working with the following change to `clearance/test_unit`:

```ruby
require 'clearance/testing/deny_access_matcher'
require 'clearance/testing/helpers'

ActionController::TestCase.class_eval do
  include Clearance::Testing::Helpers
  include Clearance::Testing::Matchers
  extend Clearance::Testing::Matchers
end
```

Basically, the only change is that I'm both including and extending the matchers. I borrowed that approach from shoulda-matchers.

Then I can write the following vanilla test unit test:

```
  def test_guest_is_denied_access
    get :index
    assert deny_access.matches?(@controller)
  end
```

This works, but is obviously not great. Additionally, I found a number of problems with the matcher in general while investigating:

1. It will blow up if you are testing a controller that doesn't include `Clearance::Controller` because it is dependent on `signed_in?`.

2. It assumes you want to redirect when denying access. This isn't the case for API requests, for example.

3. It assumed you have configured clearance to redirect to '/' (the default) for signed in users.

4. It (obviously) has no tests itself.

To be honest, I don't think I've ever used this matcher and I'm leaning towards deprecating it (possibly extracting to a gem) given its problems and the fact that I think it's intent is very easily replicated in straight rspec or minitest and in that way leaves the user in charge of how they want to assert denied access (for the aforementioned API scenario, for example).

**Comment by jferris** [comment]
>  I really know nothing about shoulda context and cant explain why this happens or what a workaround could be?

Using matchers in shoulda-context happens at the class level, so they need to be extended onto the test case class and not mixed in as instance methods.

> To be honest, I don't think I've ever used this matcher and I'm leaning towards deprecating it.

This matcher was originally just used internally in Clearance's own specs, but it became part of the public API because the controller method is also public.

I think it would be worthwhile pare down the authorization logic in Clearance to only explicitly handling situations where authentication is required (redirecting to the sign in page). I think that would include removing this matcher and the `deny_access` helper.

**Comment by derekprior** [comment]
> Using matchers in shoulda-context happens at the class level, so they need to be extended onto the test case class and not mixed in as instance methods.

I tried all combinations of extend/include. They all have this issue. When you execute `get` in `setup` you don't have access to `request` in `should`.

**Comment by derekprior** [comment]
@davidgf I'm not in a position to fix this issue and in the year and a half it's been open we haven't had anyone outside of rspec users at thoughtbot else chime in either. I'm going to close this issue for now. I'm still considering deprecating this matcher and removing it from 2.0, but I'll make that decision as I'm working on 2.0.

If you found a solution to this issue and want to contribute let me know and I'll re-open.
