### ISSUE TITLE
Use rails session instead of a cookie

### ISSUE THREAD

**Issue by arthurnn** [thoughtbot/clearance#510]
Why clearance use a separate cookie to save the token? any particular reason. 
Saving the current user id on rails session would probably make things easier. 
Thoughts?

**Comment by derekprior** [comment]
What kind of things would be easier?

One reason I can think of not to do this is that currently clearances
cookie policy can be different than your rails session cookie.

**Comment by jferris** [comment]
Session cookies are destroyed when the user closes their browser. The Clearance `REMEMBER_TOKEN` cookie needs to persist between sessions to remember the user.

**Comment by jjb** [comment]
It's very non-standard to not use the built-in rails sessions, which also gives access to all the conventions and libraries that one might be accustomed to. It would be good to have some documentation about this in the readme — what the situation is, and what the rationale is. If that could be expressed here, I could put together a PR for the readme (and/or wiki documentation).

**Comment by derekprior** [comment]
> It's very non-standard to not use the built-in rails sessions,

I'm sorry, but whose standard?

> It would be good to have some documentation about this in the readme — what the situation is, and what the rationale is.

I think Joe and I provided two decent examples here.

Are there specific problems you feel this creates?

**Comment by jjb** [comment]
HI @derekprior, thanks for your quick response. Sorry if I sounded too complainy :)

> whose standard?

Yes, "standard" is perhaps an imprecise term. I meant to say:

* in my experience (using rails since 2007), it's uncommon for a library which is only used in rails and which needs to persist identity based on web browser instance to not use the built-in session management capabilities of rails.
* the benefits of using the built-in rails session management are:
 * confidence in the security model
 * familiarity with the configuration (e.g. configure rails session domain, https-only)
 * familiarity with the behavior (e.g. clearing rails session signs out the user)
 * ability to leverage other libraries (e.g. db-persisted sessions)


> currently clearances cookie policy can be different than your rails session cookie

I've never encountered a need for this but I suppose you and others have, so okay that's interesting. I see it as a drawback though, especially since clearance does use the rails session for some things. So one can't just turn off rails sessions entirely in order to simplify the configuration.

> Session cookies are destroyed when the user closes their browser. The Clearance `REMEMBER_TOKEN` cookie needs to persist between sessions to remember the user.

If the rails session `expire_after` configuration is given a value, then the cookie is not destroyed when the user closes their browser. I imagine @jferris is well aware of this though, so I'm not sure what he's referring to here.

**Comment by jjb** [comment]
> Are there specific problems you feel this creates?

Good question :) When debugging something I was a bit confused about how things worked, which lead me here. The drawbacks listed above are some of the problems, but they aren't dealbreakers. I think a larger problem is that clearance does a lot of the work very early in a middleware, which makes it less configurable, so I can't solve problems like this one: https://github.com/thoughtbot/clearance/issues/713

**Comment by jferris** [comment]
> If the rails session expire_after configuration is given a value, then the cookie is not destroyed when the user closes their browser.

That's true - the user can configure their session to be long-lived. The default is to create a session cookie, which extends the life of the browser session.

I think there are arguments to be made for using cookies or using the session, but I don't think either is obviously the correct choice. We used a cookie, because we wanted long-lived user sessions in a world where the Rails session is short-lived by default.

Using the Rails session would mean that Clearance would work differently depending on the application session setup, which is more confusing for the maintainers if nothing else.

**Comment by rogercampos** [comment]
Clearance does the right thing using an independent cookie. The meaning of session depends on the application, and authentication is not always tied to session. Ej: an ecommerce site may use the session to store checkout related data, and a user needs to be able to make two consecutive orders while staying authenticated.
