### ISSUE TITLE
Password confirmation

### ISSUE THREAD

**Issue by nickcoyne** [thoughtbot/clearance#567]
We're considering switching from Devise to Clearance for new projects, but I notice that it doesn't offer functionality for a password confirmation field on sign-up. I'm interested in the logic behind this decision, and also any pointers to easily add a password confirmation field. Thanks!

**Comment by derekprior** [comment]
Clearance is intended to be an opinionated engine on these things. It doesn't have a password confirmation field during sign up or do email confirmation of signups (out of the box or even via twiddling config) because we find these things to be more annoying than beneficial.

That said, it's certainly possible to do both of these things. You'd need to:

1. Make sure you user has the attr_accessor for the confirmation field.
2. Add the validation for the confirmation on user
3. Add the confirmation field to your view.

I think that should do it, even with the default controllers (no need to override).

**Comment by nickcoyne** [comment]
Thanks. I get that Clearance has an opinion (which I appreciate). I was just wondering about the reasoning behind this specific opinion. I know some of our users expect a confirmation field to mitigate password typos. 

In other words I'm trying to weigh up whether I stick with the defaults (and possibly have to explain to clients why we don't have such a field), or make the changes as you suggested above.

Thanks again.
