### ISSUE TITLE
Validate email address is entered for passwords#create

### ISSUE THREAD

**Issue by manuelmeurer** [thoughtbot/clearance#601]
Currently there is no error message when someone tries to reset the password and enters no email address. The passwords controller even tries to find a user without an email address.
Wouldn't the default case be that you'd want an error message to appear if no email address is entered?

**Comment by derekprior** [comment]
This is a bit harder to address than I would like due to the fact that many of the forms do not have backing models which to call validate on. I could write those easily but that'd be a breaking change for people who have generated the views.

We could do validations in the controllers based on params, but I don't really love that solution. One stop-gap would be to add HTML5 validations to forms. I'll likely kick the tires on this.

**Comment by manuelmeurer** [comment]
Yeah I think introducing a model and validations would be overkill. But logically, looking at the controller, I would expect a check that `params[:password][:email]` is present before this line:
https://github.com/thoughtbot/clearance/blob/781e9a9fd99bad27b45fa10e1c3b019b8caa31a5/app/controllers/clearance/passwords_controller.rb#L66
