### ISSUE TITLE
Simple way to use User model as a profile

### ISSUE THREAD

**Issue by nickmjones** [thoughtbot/clearance#614]
I'm trying to override the default User behavior to add some profile-like fields (like name, Twitter handle etc.). I've successfully added new fields and overridden the user controller, but upon editing a user I get `No route matches [PATCH] "/users/1"`

Is there a simple, conventional guide to modifying the User model and using it both to authenticate against but also to use as a public-facing profile within an application?

**Comment by derekprior** [comment]
It sounds like you already figured out how to collect the additional fields on registration? If so, that was probably the hard part! The model is yours to do with what you'd like, but several people have run into some issues when adding new fields to collect at registration because that requires overriding the clearance controllers themselves. There is only API documentation on the various controller methods

As for editing or updating users, clearance does not implement this functionality. You will need to add your own routes and controller/controller actions for this and handle it the same as any other action. Clearance only provides users#new and users#create.

**Comment by nickmjones** [comment]
Hey @derekprior, thanks very much for your gracious response! You've pointed me in the right direction, and I have a light version of what I need running now. Thanks again for the response. I'll continue to poke around and try to learn more. Who knows, maybe I can even contribute some documentation at some point.
