### ISSUE TITLE
Not working with a Rails 5 api

### ISSUE THREAD

**Issue by GCorbel** [thoughtbot/clearance#619]
Hi,

I have a Rails 5 api and I try use Clearance in it but have this error : `No such middleware to insert after: ActionDispatch::ParamsParser (RuntimeError)`. Here is a middleware in dev : 

    use Rack::Sendfile
    use ActionDispatch::Static
    use ActionDispatch::LoadInterlock
    use ActiveSupport::Cache::Strategy::LocalCache::Middleware
    use Rack::Runtime
    use ActionDispatch::RequestId
    use Rails::Rack::Logger
    use ActionDispatch::ShowExceptions
    use ActionDispatch::DebugExceptions
    use ActionDispatch::RemoteIp
    use ActionDispatch::Reloader
    use ActionDispatch::Callbacks
    use ActiveRecord::Migration::CheckPending
    use ActiveRecord::ConnectionAdapters::ConnectionManagement
    use ActiveRecord::QueryCache
    use Rack::Head
    use Rack::ConditionalGet
    use Rack::ETag
    use Rack::Cors
    use ActionView::Digestor::PerRequestDigestCacheExpiry
    run Tiny::Application.routes

And for production : 

    use Rack::Sendfile
    use ActionDispatch::LoadInterlock
    use ActiveSupport::Cache::Strategy::LocalCache::Middleware
    use Rack::Runtime
    use ActionDispatch::RequestId
    use Rails::Rack::Logger
    use ActionDispatch::ShowExceptions
    use ActionDispatch::DebugExceptions
    use ActionDispatch::RemoteIp
    use ActionDispatch::Callbacks
    use ActiveRecord::ConnectionAdapters::ConnectionManagement
    use ActiveRecord::QueryCache
    use Rack::Head
    use Rack::ConditionalGet
    use Rack::ETag
    use Rack::Cors
    run Tiny::Application.routes

What's the best place for the middleware? Why not to simply put it at the end?

**Comment by GCorbel** [comment]
I fixed it but I had to do this : 

    class ApplicationController < ActionController::API
      def self.helper_method(*args)
      end
      def self.hide_action(*args)
      end

      include Clearance::Controller
    end

I can do another PR to fix the issue if you're interested.

**Comment by j-dexx** [comment]
Rails 4 has the following middleware in production

```
use Rack::Sendfile
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x000000033a60f8>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
```

So maybe after ActiveRecord::QueryCache?

**Comment by GCorbel** [comment]
I think we will dependent of the existing middlewares. Is there a reason to not place it at the end?

**Comment by j-dexx** [comment]
Not that I can see, but the maintainers might want it in a specific place.

There are other things that need to be addressed for rails 5 though, for example rails/rails#18336 removes `hide_action` which means authorization.rb and authentication.rb will need changing

**Comment by GCorbel** [comment]
@j-dexx , I agree. I monkey patched some parts. I will check to do a PR for rails 5 later.

**Comment by derekprior** [comment]
The middleware has always been inserted at a set point in the stack ever since we started using middleware. The git history doesn't tell us why. I'd want to do several manual tests before changing it and speak to some people here to see if anyone has context on why it's located where it is.

As for any other Rails 5 issues, please open new, focused issues as you find them. This will make tackling, testing, and reviewing these easier.

I do not currently have the time to review these issues, but may next week.

**Comment by GCorbel** [comment]
I agree with you @derekprior . No problem for the delay, happy Christmas time !

**Comment by j-dexx** [comment]
Makes sense to me, will do.  I echo GCorbel - no rush, enjoy Christmas.

**Comment by zernie** [comment]
Here's the relevant commit from rails: https://github.com/rails/rails/commit/a1ced8b52ce60d0634e65aa36cb89f015f9f543d
> do not instantiate a param parser middleware
we don't actually need a param parser middleware instance since the
request object will take care of parsing parameters for us.  For now,
we'll just configure the parameter parsers on the request in this class.

**Comment by jferris** [comment]
I originally added the middleware. It had to go in a specific place because of how it interacted with  cookies. Rails writes its cookies in the `ActionDispatch::Cookies` middleware, so Clearance's middleware had to go after or cookies would get clobbered.

It looks like this commit moved it from cookies to params parser: https://github.com/thoughtbot/clearance/commit/f2d453648b0ef1204d56dd6fc4d1c0c7bdae4f07

I'm not sure why that was done. It seems like it makes more sense to pair it with the cookies middleware, since it's dependent on cookie values and not parameters.

**Comment by derekprior** [comment]
@jferris Rails api default middleware stack (see original report in this thread) does not include `ActionDispatch::Cookies` either.

If I had to guess - and this is only the guess - the change you linked was made because at the time, the rails api project *did* include params parser and that also conveniently happened to be after `ActionDispatch::Cookies` in the default rails stack. Like I said, just a guess.

It doesn't appear we depend on `ActionDispatch::Cookies` being present, so the suggestion to put it after whatever rails decides is its middleware stack seems like a good one.

**Comment by derekprior** [comment]
> It doesn't appear we depend on `ActionDispatch::Cookies` being present

Here I'm only going off of what people in this thread have said and that the linked commit solved the problem in an older version of rails-api.

**Comment by derekprior** [comment]
I have merged the middelware position change. I'm slowly working through Rails 5 issues and hope to have something working for folks to test soon.

**Comment by drale2k** [comment]
I am having the same issue with Rails 5 beta 2 and Clearance 1.12.1

**Comment by derekprior** [comment]
Hi @drale2k, as mentioned there is progress on the master branch and there is more progress in PRs. Clearance does not yet support Rails 5.

**Comment by drale2k** [comment]
Hi @derekprior. Because of this post i thought it was fixed

> I have merged the middelware position change. I'm slowly working through Rails 5 issues and hope to have something working for folks to test soon.

The issue seems to be fixed in the `dp-rails5-deprecations` branch but i will continue implementing it later and see if there are other issues left (i guess there are since you're saying it does not support Rails 5 yet)

**Comment by JoshSmith** [comment]
@derekprior we came upon this issue just recently and used @GCorbel's fix. Is there somewhere to track progress on this since this particular issue is closed?

**Comment by derekprior** [comment]
@JoshSmith What version of Clearance are you using? 1.13.0 was the first version that purported to support Rails 5. The releases page or the NEWS file have more detail.

**Comment by JoshSmith** [comment]
@derekprior I'm on 1.14.1 right now.

**Comment by srt32** [comment]
I am working on a Rails 5 API app and the workaround in https://github.com/thoughtbot/clearance/issues/619#issuecomment-166772517 got me around the first error I saw but when I went to `/sign_in` I got just a white screen (the html page was empty). I imagine it has something to do with missing middleware since it's an API only app. Anyone else using an API app with clearance run into this issue? Thanks!
