### ISSUE TITLE
before_filter is deprecated in 5.0

### ISSUE THREAD

**Issue by sonalkr132** [thoughtbot/clearance#684]
I am using rails 5.0.0.rc2 and it gives following deprecation pointing at file for clearance: 
> DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead.

clearance version: 1.14.1

Related: #519

**Comment by derekprior** [comment]
What file does it point at?

**Comment by sonalkr132** [comment]
This line: https://github.com/rubygems/rubygems.org/blob/master/lib/clearance_backdoor.rb#L9

**Comment by derekprior** [comment]
That line appears in your backtrace because that piece of middleware is enabled in your test environment and thus is active on every request.

I'm fairly certain we've removed all calls to `before_filter` in the Rails 5.0 compatible versions of Clearance. Have you tried searching code in your own app to see if `before_filter` is used there? Is there a full stack trace you can share for this warning?

**Comment by sonalkr132** [comment]
It was coming from doorkeeper. I had just one line of stack trace:
```
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from call at /home/user/rubygems.org/lib/clearance_backdoor.rb:10)
```

Sorry, I couldn't tell. Had to put `caller` right in `ActiveSupport::Deprecation` to find out.
Thank you for your time, anyway. :blue_heart:
