### ISSUE TITLE
rails d clearance:views deletes application.html.erb

### ISSUE THREAD

**Issue by lifeiscontent** [thoughtbot/clearance#701]
Yep.

**Comment by pedrosmmoreira** [comment]
I think the issue to address here is if Clearance should even generate an application.html.erb file. I am thinking this was added as a convenience to help you get started, but since the suggested/necessary additions to layout are printed to STDOUT on install, it would be better to not touch the layout file.

I'll open a PR with a change in order to gather some opinions.

**Comment by derekprior** [comment]
This is being discussed in #702. Closing this issue.
