### ISSUE TITLE
Q: post-sign_in hook

### ISSUE THREAD

**Issue by jrochkind** [thoughtbot/clearance#704]
I have had need to have something run _after_ a succesful sign-in. Calling some hook from an associated engine that needs certain things to happen after sign-in, is my use case. Or, hypothetically, one could imagine logging the sign_in to some auditing system. 

Is there any recommended way to do this?

I've been over-riding `sign_in` in `ApplicationController`, to first call `super` then do my custom things. But this feels dirty, and additionally I realize that `Controller#sign_in` isn't neccesarily the only way to sign in to Clearance, code somewhere could also be doing `request.env[:clearance].sign_in user`, which would skip my custom logic. 

Any thoughts? Any better way to do this? Would this be a welcome PR to clearance?

**Comment by jessmartin** [comment]
I have the same question. Surprised there's not a better way to do this.

For me, I'd like to track every sign-in in our analytics platform.

I'm also interested in tracking sign ups, sign outs, and password changes.

**Comment by jessmartin** [comment]
Ok, I found a way to accomplish this @jrochkind. It's not a one-liner by any means.

Rather than overriding `sign_in` in `ApplicationController`, override the `SessionsController` and use an `after_action` filter.

Here's some rough code:

app/controllers/sessions_controller.rb:
```ruby
class SessionsController < Clearance::SessionsController
  after_action :track_sign_in, only: :create

  private

  def track_sign_in
    analytics.track(:sign_in_create)
  end
end
```

Also, you have to update `routes.rb` to point to this new controller:
```ruby
  resource :session, controller: "sessions", only: [:create]
```

You're right that someone could still hit `request.env[:clearance].sign_in` directly and bypass this, but for me, every sign-in takes place from a web form, so I'm cool with it.

Hope that's helpful.

**Comment by derekprior** [comment]
Overriding `sign_in` is a perfectly valid thing to do. You may also use a `SignInGuard` (see documentation) and place this guard last in the stack.
