### ISSUE TITLE
Reset password does not deliver_later

### ISSUE THREAD

**Issue by tjshipe** [thoughtbot/clearance#716]
In PasswordsController#create the deliver_email method checks if the mail object responds to #deliver_later, but calling respond_to modifies the object which then raises an exception preventing delivery.

``` ruby
def deliver_email(user)
  mail = ::ClearanceMailer.change_password(user)

  if mail.respond_to?(:deliver_later)
    mail.deliver_later
  else
    mail.deliver
  end
end
```

The exception was introduced in this pull request to rails:

https://github.com/rails/rails/pull/24457/files

**Comment by derekprior** [comment]
> calling responds_to modifies the object

sigh.

I guess we can call `deliver_later`, catch a `NoMethodError` and then call `deliver`? Or would that not work either?

**Comment by derekprior** [comment]
This seems like a Rails bug to me, so I've opened https://github.com/rails/rails/issues/26916

**Comment by derekprior** [comment]
@tjshipe I am looking into this but found that I can't reproduce it. We do exercise this code path in our tests (passwords_controller_spec.rb, line 25) and I haven't seen this fail. If, before calling `deliver_later`, I do something like `mail.subject = 'foo'` then I trigger the error. Otherwise, delivery appear to happen as you would expect. I tested with Rails 5.0.1, although Rails' own changelogs indicate there are no changes to ActionMailer since 5.0.0, so this shouldn't have been fixed from the Rails side.

Are you able to reproduce this? I will re-open if so.
