### ISSUE TITLE
Install fails if database not-yet-created

### ISSUE THREAD

**Issue by coreyward** [thoughtbot/clearance#737]
Running `bin/rails generate clearance:install` when a database has not yet been created results in the following error: 

```
rescue in connect': FATAL:  database "example_development" does not exist (ActiveRecord::NoDatabaseError)
```

Which traces back to this line in Clearance:
`lib/generators/clearance/install/install_generator.rb:105:in `users_table_exists?'`

This is sort of expected, but it would be nice if it were handled more elegantly. I can patch the `users_table_exists?` method to handle this case if someone can point me to an example of how Clearance prefers to write information back to the prompt.

**Comment by magikid** [comment]
How were you thinking of handling it?

**Comment by derekprior** [comment]
I think the error as it's displayed is actually pretty good. It could be changed by rescuing `NoDatabaseError` and raising an exception with a better message (`run rails db:create first` or something) but even this has complications because versions of Rails < 5 would run `rake db:create` (which will also work on 5+ but may be confusing to people who find the original error confusing).
