### ISSUE TITLE
Integration with Rails' 5.2 Current

### ISSUE THREAD

**Issue by dwightwatson** [thoughtbot/clearance#779]
Hey, are there any plans to integrate Clearance with the new `Current` model that will be shipping with Rails 5.2? It would allow developers to call `Current.user` instead of using the `current_user` method and I suspect that would become more standardised as Rails goes forward.

For more information [you can see the implementation of the `ActiveSupport::CurrentAttributes` here](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/current_attributes.rb).

**Comment by rickychilcott** [comment]
You can set this yourself just after you `include Clearance::Controller` in your `ApplicationController` by adding a file to `app/controller/concerns` called `set_current_user.rb` and using the following:

```ruby
module SetCurrentUser
  extend ActiveSupport::Concern

  included do
    before_action :set_current_user
  end

  private
    def set_current_user
      ::Current.user = current_user
    end
end
```

You'll need to add your own `Current` class at `app/models/current.rb`, that would look something like:

```ruby
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end
```

I'm using this myself, but I'm not sure `Current` will catch on 100% throughout the community. This could become part of Clearance, but it's really not hard to own yourself, and it honestly doesn't give you much. It also makes testing a little more challenging.

I only did it to set `Time.zone` and `I18n.locale` per user, but have considered removing it because of the testing implications.

**Comment by mjankowski** [comment]
I'm going to close this on the assumption that the previous comment provides enough information and context for people to implement this alongside a clearance-backed app if they wanted to.
