### ISSUE TITLE
Question: Multiple User types

### ISSUE THREAD

**Issue by Immortalin** [thoughtbot/clearance#796]
If there were two types of users e.g. Buyers and Sellers, how should the signup be implemented?

**Comment by nipe0324** [comment]
Maybe It could not be possible and easy now. Because clearance authentication depends on `Clearance.configuration.user_model` set in here https://github.com/thoughtbot/clearance/blob/master/lib/clearance/configuration.rb#L108-L110

And `Clearance.configuration.user_model` is used some places as below.

https://github.com/thoughtbot/clearance/blob/master/lib/clearance/authentication.rb#L27-L31
https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/passwords_controller.rb#L87-L90
https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/users_controller.rb#L52-L56

**Comment by Immortalin** [comment]
Currently I am using User model with enums and additional columns for each additional role. I will consider this solved for now. Enums and additional columns are not perfect as it requires very tricky code to deal with relations. 

https://stackoverflow.com/questions/5294775/same-model-for-two-belongs-to-associations
