### ISSUE TITLE
generated user model migration does not respect `config.generators`

### ISSUE THREAD

**Issue by namiwang** [thoughtbot/clearance#809]
repro:

config `application.rb`

```
    config.generators do |g|
      g.orm :active_record, primary_key_type: :uuid
    end
```

run `rails generate clearance:install`

generated migration

```
...
create_table :users do |t|
...
```

expected

```
...
create_table :users, id: :uuid do |t|
...
```

**Comment by mjankowski** [comment]
Is the desired behavior here that instead of just doing a dumb copy of this template - https://github.com/thoughtbot/clearance/blob/master/lib/generators/clearance/install/templates/db/migrate/create_users.rb.erb - you would instead want the clearance-generated migration to run "through" the rails migration generation stack, so that options like that were applied?

This would be the equivalent of running `rails g migration CreateUsers email:string ...` instead of doing the copy? (and thus, rails would generate the migration instead of clearance copying a migration)
