### ISSUE TITLE
1.16.2 breaks follow_redirect! in tests

### ISSUE THREAD

**Issue by navied** [thoughtbot/clearance#821]
After upgrading to 1.16.2 for some reason it loses the authentication when a follow_redirect! is performed and redirects back to the login screen. We are using the backdoor properly in the test environment as well. We fixed it by monkey patching follow_redirect to accept an as: user field. 

Not sure if this was the intended effect with the new version.

**Comment by mjankowski** [comment]
Thanks for the report.

Can you provide some (redacted if needed) test code that was working on 1.16.1 and now fails? Alternately, can you provide a failing spec against clearance itself?

**Comment by navied** [comment]
@mjankowski thanks for the response. 

In the process of trying to recreate the issue I believe I have honed in on the exact problem. In 1.16.1 when you explicitly set config.cookie_domain it did not effect the test environment but with 1.16.2 unless the cookie domain is set to "example.com" for the test env the follow_redirect! fails. 

You can see it fail here: https://github.com/navied/clearance_test

To make it pass all you have to do is reduce the clearance version to 1.16.1.

**Comment by mjankowski** [comment]
Thanks ... and yes, a local git bisect reveals this commit as the first one where your tests fail - https://github.com/thoughtbot/clearance/commit/cf1f03c1fc045048306de84995cd3ed06675ed31

**Comment by coneybeare** [comment]
I opened #822 and am also seeing the issue here on feature specs.

**Comment by mjankowski** [comment]
@navied I think you are correct.

In earlier versions when `cookie_domain` was set, we would actually set two cookies: a) a cookie without a domain, b) a cookie with a domain. I suspect that the first cookie without the domain was being set and was making the tests pass, despite the disconnect between the clearance `cookie_domain` setting and the "example.com" used by rack test.

In your example app, if you change the cookie domain line to:

`config.cookie_domain = Rails.env.production? ? '.example.com' : nil`

I suspect that would resolve the failures?

**Comment by navied** [comment]
Yep, setting the cookie domain to nil would solve the issues. That explanation definitely make sense on what is probably going on. Not sure if it would make sense to ignore the cookie_domain config in test environments.

**Comment by mjankowski** [comment]
Great.

I'm going to close this with the conclusion that there's not actually a bug in 1.16.2, but that instead there's behavior from prior releases that was unknowingly relied upon, and that it can be resolved by making sure the domain name being set for cookies matches whatever is being used in specs.

If that's not the case, please re-open or otherwise report back.

**Comment by leemcalilly** [comment]
Seems like it might be better to set the cookie domain for the test and dev environments in config/application.yml:
```
development:
  COOKIE_DOMAIN:    ".localhost:3000"
```

That seems like it would be easier to maintain down the road because it's crystal clear what's going on with each environment and you don't have to add a mysterious conditional to the clearance config file.
