### ISSUE TITLE
ApplicationController.renderer support

### ISSUE THREAD

**Issue by JensDebergh** [thoughtbot/clearance#848]
Rails version: 5.2.0

Problem:

I'm trying to render some pdf's inside a background job and make them available to the user. I make use of `ApplicationController.renderer.render` to process the template to html and output a pdf file.

Due to the inclusion of `Clearance::Controller` the render function is looking for a `current_user` method that is normally provided by clearance rack middleware and is lacking in this specific scenario. So it just crashes.

Is it possible to skip these for this specific rails 5 feature?

My current solution is this snippet in `ApplicationController`: 

```
  def self.render_with_signed_in_user(user, *args)
    ActionController::Renderer::RACK_KEY_TRANSLATION[:clearance] ||= :clearance
    session = Clearance::Session.new({}).tap{|i| i.sign_in(user) }
    renderer = self.renderer.new(clearance: session)
    renderer.render(*args)
  end
```

Any advice pushing me in the right direction is greatly appreciated.

Kind regards
Jens

**Comment by mjankowski** [comment]
Is this still an issue? Did you wind up finding anything more elegant?

Also, I don't quite get the issue ... is the problem something like:

- You are using `renderer` from within a background and outside of the request/response cycle
- Thus, the request/response rack env that clearance operates on is not present while the renderer is running?
- Something about the render call is executing the clearance `current_user` method, which blows up, because the full rack middleware stack is not loaded?

I wonder if you could give the renderer some rack env options to fake out something sufficient enough to at least not error? (see env notes in https://api.rubyonrails.org/v6.0.0/classes/ActionController/Renderer.html )

**Comment by JensDebergh** [comment]
Hey @mjankowski 

Exactly! Clearance is expecting specific rack middle stuff to be available but this is not available since it's being run from a background process. To my knowledge I'm also unable to provide a rack env to the renderer.

I was able to circumvent this issue by letting authenticated users initiated a pdf rendering request which will go through the background job, but I'm actually rendering a hidden view only known to the server under a hidden name which has clearance disabled.

Not an ideal fix but it works

Maybe I should raise this issue on the rails repo aswel. Since this is really a limitation of the current renderer in rail.

**Comment by mjankowski** [comment]
Thanks, I'm going to close this on the assumption that this is not narrowly a clearance problem, but would be an issue for anything interacting with the rack env in this way.

If you find a nicer solution please follow up here -- or if there's a straightforward change we could make in clearance to make the workaround easier, we'd be open to that as well.
