### ISSUE TITLE
remember_token == nil

### ISSUE THREAD

**Issue by gingerlime** [thoughtbot/clearance#922]
We're in the process of (hopefully) migrating from devise to clearance, and I bumped into a potential edge case.

Our users already have a `remember_token` attribute, and for some users this is `nil`. It seems like Clearance relies on [a `before_create` action](https://github.com/thoughtbot/clearance/blob/ce17d2d6d861bb3415602c388bbf5bda8b5fceec/lib/clearance/user.rb#L168) to set the remember token initially. However, when the user already exists, and their token is nil, then whilst sign_in is successful, there's no value for the remember_token cookie to set ...

Here's a rough test case that demonstrates it (if added to `spec/clearance/session_spec.rb`)

```ruby
  context 'user without remember_token' do
    before do
      user.remember_token = nil
      session.sign_in(user)
    end

    it "adds cookie to headers" do
      session.add_cookie_to_headers(headers)

      # this passes
      expect(session.signed_in?).to be_truthy

      # this fails
      expect(headers['Set-Cookie']).to match(/remember_token=.+; HttpOnly/)
    end
  end
```

I can work around it and set the remember_token if it's missing outside of clearance, but I'm wondering if the project might want to consider automatically setting the user remember_token if it doesn't exist?

**Comment by eebs** [comment]
I'm hesitant to introduce functionality directly into Clearance that handles cases such as these. I think we should leave the migration strategy up to the individual applications as it will vary on a case by case basis. Does that seem reasonable?

**Comment by gingerlime** [comment]
Thanks for getting back to me @eebs. I'm not sure it only applies to a migration strategy (even though I think this should also be a use-case if you hope to increase adoption, but that's entirely your own priority). If this attribute is being reset for whichever reason, then the user is essentially unable to sign in. I guess it's not a very common case either way though.

**Comment by eebs** [comment]
If the remember_token is modified outside of Clearance either due to migrating from another library or for some other out-of-band change, I'm not sure Clearance should step in to "fix" it. I can imagine that someone may not want Clearance to automatically regenerate a remember token.

To address your specific case and others like it though, I'd recommend using an `after_action` callback, a [SignInGuard](https://github.com/thoughtbot/clearance/blob/eeb59022e946179f89e2a8239b0223a6eeaebdd4/lib/clearance/sign_in_guard.rb), or a migration task to rectify the situation.

If you'd like to have the remember token reset when a user signs in you could create a sign in guard like this

```ruby
class ResetRememberTokenGuard < Clearance::SignInGuard
  def call
    if signed_in? && current_user.remember_token.nil?
      current_user.reset_remember_token!
    end
    next_guard
  end
end
```
This will regenerate the reset token when a user signs in if it's currently nil.

Another option would be to reset them all at once from a console or rake task:

```ruby
User.where(remember_token: nil).find_each(&:reset_remember_token!)
```

Hope this helps!

**Comment by gingerlime** [comment]
Thanks @eebs. This works, but to me feels a bit awkward, I have to say. A "guard" sounds like something that simply checks and says yes/no. This guard doesn't just check, but also updates the user ... personally it doesn't feel like the logical place for this.

Besides that, obviously users who migrate to clearance will have to know about this and add this guard in certain conditions. I think clearance can be more robust if it handles this "natively", but that's just my intuitive opinion about this. It's obviously your call.
